# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed39308d8ffe27762b8c022879ddfeb1cd8c832b1f452f383c0905d22caa5eef9ad3bdce422ba2fadd2af3aee0b77a10e47244f28954c6695d4d0dc26ecd3c6d

test:
  secret_key_base: 20de2fca1164a7bbe4f966d0ef4cf8eb15636526c566ac838233c4eb7a1b7ca07396a6cf79d37d0cc197a668f6e26e07af7fdb4f2d61db027cb91842efbc3df3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
